export const GAME_ACTION_TYPES = {
  SET_CURRENT_IMAGE: "SET_CURRENT_IMAGE",
  INCREMENT_COUNTER: "INCREMENT_COUNTER",
  RESET_COUNTER:"RESET_COUNTER",
  ADD_ITEM_TO_SHOWING_ARRAY: "ADD_ITEM_TO_SHOWING_ARRAY",
  REMOVE_ITEM_FROM_SHOWING_ARRAY:"REMOVE_ITEM_FROM_SHOWING_ARRAY",
  RESET_SHOWING_ARRAY:"RESET_SHOWING_ARRAY",
  GAME_STATE: "GAME_STATE",
};
